### ISSUE TITLE
Can we resucite this project?

### ISSUE THREAD

**Issue by sebassdc** [BibleJS/bible.js#10]
Hey how can i help. Do you still maintaining this or i can do a fork

**Comment by IonicaBizau** [comment]
@sebassdc Contributions are welcome! 🍀 

What exactly would you like to improve?

**Comment by sebassdc** [comment]
I have a few ideas. Maybe i could refactor the lib/index.js file from this repo to improve readability. Then im not sure about how the data is transfered. I think we can make and npm package instead of cloning the versions from github. Also we can disscus about a way of storing the bibles on local with a eficient an easy to work with format. Maybe json could work. Also we can host the data on firebase wich its for free. Then we can make a gui a reader a lector. All in our beloved language. :D

**Comment by IonicaBizau** [comment]
I'm for it!

I started organizing my GitHub repos a little bit and I found this module, so let's do that!

Everyone who wants to join the organization is welcome! Just let me know.

**Comment by IonicaBizau** [comment]
Tweeted here: https://twitter.com/IonicaBizau/status/1123535418279047168
